on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
jobs:
  show_env:
    runs-on: ubuntu-latest
    env:
      IS_BUG: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
    steps:
      - run: |
          env | sort
          echo "${{ toJson(github.event.pull_request.labels) }}"
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"

