on:
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
  pull_request:
    branches:
      - main

jobs:
  show_env:
    runs-on: ubuntu-latest

    steps:
      - run: env | grep GITHUB | sort

