on:
#  pull_request_target:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
jobs:
  show_env:
    runs-on: ubuntu-latest

    steps:
      - name: show env
        env:
          EVENT_NAME:  ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
        if: |
          (github.event.action == 'labeled') || (github.event.action == 'unlabeled')
        run: |
          echo ${EVENT_NAME}
          echo ${EVENT_ACTION}
