on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - dev 

jobs:
  show_env:
    runs-on: ubuntu-latest

    steps:
      - run: env | grep GITHUB | sort

